### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by kartik3165** [razorpay/razorpay-java#127]
java.lang.NoSuchMethodError:
No virtual method
startSmsUserConsent(Ljava/
lang/String:)Lcom/google/
android/gms/tasks/Task; in
class Lcom/google/android/
gms/auth/api/phone/
SmsRetrieverClient; or its
super classes (declaration of
'com.google.android.gms.auth.
api.phone.SmsRetrieverClient'
appears in base.apk!
classes4.dex)

**Comment by Puneet1796** [comment]
You can ignore this error, it's for their SDK. Your code will work fine.

**Comment by ankitdas13** [comment]
@Puneet1796 sorry for the long delay . It seems this issue is not related to the SDK, could you please let us know is this issue has been fixed ?

**Comment by ankitdas13** [comment]
@kartik3165 Closing this issue for now, unrelated to this package if the issue still persists , create a new issue in this [repo](https://github.com/razorpay/razorpay-android)

**Comment by dhavalpatel666** [comment]
error - 


  java.lang.NoSuchFieldError: No static field NO_OPTIONS of type Lcom/google/android/gms/common/api/Api$ApiOptions$NoOptions; in class Lcom/google/android/gms/common/api/Api$ApiOptions; or its superclasses (declaration of 'com.google.android.gms.common.api.Api$ApiOptions' appears in base.apk!classes2.dex)
        at com.google.android.gms.auth.api.phone.SmsRetrieverClient.<init>(com.google.android.gms:play-services-auth-api-phone@@17.5.1:1)
        at com.google.android.gms.internal.auth-api-phone.zzab.<init>(com.google.android.gms:play-services-auth-api-phone@@17.5.1:1)
        at com.google.android.gms.auth.api.phone.SmsRetriever.getClient(com.google.android.gms:play-services-auth-api-phone@@17.5.1:1)
        at com.razorpay.CheckoutPresenterImpl.onLoad(CheckoutPresenterImpl.java:758)
        at com.razorpay.CheckoutBridge$1.secure(CheckoutBridge.java:26)
        at com.razorpay.CheckoutPresenterImpl.executeWebViewCallback(CheckoutPresenterImpl.java:1235)
        at com.razorpay.CheckoutPresenterImpl.access$800(CheckoutPresenterImpl.java:49)
        at com.razorpay.CheckoutPresenterImpl$17.run(CheckoutPresenterImpl.java:1221)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6810)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
