### ISSUE TITLE
Unable to Make Test Payment Showing this error??

### ISSUE THREAD

**Issue by tanishq14developer** [razorpay/razorpay-java#135]
E/com.razorpay.checkout: Webview JS Error: Uncaught ReferenceError: otpPermissionCallback is not defined
2021-10-07 15:09:31.493 22413-22413/com.tanishq.creditscrore I/chromium: [INFO:CONSOLE(1)] "Uncaught ReferenceError: otpPermissionCallback is not defined", source: https://api.razorpay.com/v1/checkout/public?version=1.6.12&library=checkoutjs&platform=android (1)
2021-10-07 15:09:31.498 22413-22413/com.tanishq.creditscrore E/ActivityThread: Activity com.razorpay.CheckoutActivity has leaked IntentReceiver com.razorpay.AutoReadOtpHelper@5ba677a that was originally registered here. Are you missing a call to unregisterReceiver()?
    android.app.IntentReceiverLeaked: Activity com.razorpay.CheckoutActivity has leaked IntentReceiver com.razorpay.AutoReadOtpHelper@5ba677a that was originally registered here. Are you missing a call to unregisterReceiver()?
        at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1602)
        at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1378)
        at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1624)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1590)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1578)
        at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:679)
        at com.razorpay.CheckoutPresenterImpl.startSmsRetrieverForSavedCardsOTP(CheckoutPresenterImpl.java:828)
        at com.razorpay.CheckoutPresenterImpl.onLoad(CheckoutPresenterImpl.java:819)
        at com.razorpay.l__d$.secure(CheckoutBridge.java:27)
        at com.razorpay.CheckoutPresenterImpl.executeWebViewCallback(CheckoutPresenterImpl.java:1257)
        at com.razorpay.CheckoutPresenterImpl.access$700(CheckoutPresenterImpl.java:49)
        at com.razorpay.z$_w$.run(CheckoutPresenterImpl.java:1243)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:8019)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

**Comment by Puneet1796** [comment]
Your error may not be related to this log. Try logging the `code` and `response` parameters that you get in `onPaymentError` callback. You will possibly be able to see the error there.

**Comment by ankitdas13** [comment]
@tanishq14developer Sorry for the long delay. seems like you are using [razorpay-android](https://github.com/razorpay/razorpay-android). Could you please confirm this first and if this issue has been resolved, please let us know.

**Comment by tanishq14developer** [comment]
no still there

**Comment by ankitdas13** [comment]
@tanishq14developer Thank you for letting us know that you are still experiencing this issue. could you please raise this same issue in this [repo](https://github.com/razorpay/razorpay-android) ?

**Comment by ankitdas13** [comment]
@tanishq14developer

**Comment by ankitdas13** [comment]
Closing this issue for now due to not getting any response, also this issue is not related to this repo
