### ISSUE TITLE
Intent Filter leaked in Razorpay getting

### ISSUE THREAD

**Issue by tanishq14developer** [razorpay/razorpay-java#263]
Activity com.razorpay.CheckoutActivity has leaked IntentReceiver com.razorpay.AutoReadOtpHelper@c42c9c4 that was originally registered here. Are you missing a call to unregisterReceiver()?
    android.app.IntentReceiverLeaked: Activity com.razorpay.CheckoutActivity has leaked IntentReceiver com.razorpay.AutoReadOtpHelper@c42c9c4 that was originally registered here. Are you missing a call to unregisterReceiver()?
        at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1876)
        at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1595)
        at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1827)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1793)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1781)
        at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:743)
        at com.razorpay.CheckoutPresenterImpl.startSmsRetrieverForSavedCardsOTP(CheckoutPresenterImpl.java:916)
        at com.razorpay.CheckoutPresenterImpl.onSubmit(CheckoutPresenterImpl.java:1056)
        at com.razorpay.O__Y_.secure(CheckoutBridge.java:158)
        at com.razorpay.CheckoutPresenterImpl.executeWebViewCallback(CheckoutPresenterImpl.java:1370)
        at com.razorpay.CheckoutPresenterImpl.access$700(CheckoutPresenterImpl.java:55)
        at com.razorpay.b$_f_.run(CheckoutPresenterImpl.java:1355)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

**Comment by ankitdas13** [comment]
@tanishq14developer This issue is not releated to this repo could you please close this issue and create new issue this [repo](https://github.com/razorpay/razorpay-android-sample-app)  ?

**Comment by ankitdas13** [comment]
This issue is not related to this repo. Please open an issue in [repo](https://github.com/razorpay/razorpay-android-sample-app) repo. Closing this issue.
