### ISSUE TITLE
Create Plan not working

### ISSUE THREAD

**Issue by AnuvadiyaHiren** [razorpay/razorpay-java#35]
Plan result = razorpayClient.Plans.create(request);

com.razorpay.RazorpayException: BAD_REQUEST_ERROR:The requested URL was not found on the server.
	at com.razorpay.ApiClient.throwException(ApiClient.java:174)
	at com.razorpay.ApiClient.processResponse(ApiClient.java:119)
	at com.razorpay.ApiClient.post(ApiClient.java:41)
	at com.razorpay.PlanClient.post(PlanClient.java:7)
	at com.razorpay.PlanClient.create(PlanClient.java:14)

**Comment by sharon-tst** [comment]
Did u got any work around on it?

**Comment by harman28** [comment]
Sorry for the delay here, noting a response anyway for anyone else who comes looking. If you're getting "URL not found", it's because the feature is not enabled on your account. You can ask for it to be enabled via your merchant dashboard, and retry.

**Comment by sharon-tst** [comment]
thank you for your response
