### ISSUE TITLE
order id generation error!!  getting null value

### ISSUE THREAD

**Issue by navinmp** [razorpay/razorpay-java#41]
azorpay.utils.RazorpayException: Unable to parse response because of null
	at com.buszaar.razorpay.utils.ApiClient.parseResponse(ApiClient.java:71)
	at com.buszaar.razorpay.utils.ApiClient.parseCollectionResponse(ApiClient.java:87)
	at com.buszaar.razorpay.utils.ApiClient.processCollectionResponse(ApiClient.java:141)
	at com.buszaar.razorpay.utils.ApiClient.getCollection(ApiClient.java:62)
	at com.buszaar.razorpay.utils.OrderClient.fetchAll(OrderClient.java:22)
	at com.buszaar.razorpay.utils.OrderClient.fetchAll(OrderClient.java:18)
	at com.razorpay.api.RazorpayApplication.main(RazorpayApplication.java:32)

**Comment by harman28** [comment]
Sorry for the delay here, we'd need a little more info to debug this, like which API was being hit and what the error response actually is. I hope this worked out for you, but if not please feel free to re-open and share more details so we can check it out at once.
